from ..tl import TLRequest as TLRequest
from ..tl.core.messagecontainer import MessageContainer as MessageContainer
from ..tl.core.tlmessage import TLMessage as TLMessage

class MessagePacker:
    def __init__(self, state, loggers) -> None: ...
    def append(self, state) -> None: ...
    def extend(self, states) -> None: ...
    async def get(self): ...
