from .. import TLObject as TLObject
from _typeshed import Incomplete

class GzipPacked(TLObject):
    CONSTRUCTOR_ID: int
    data: Incomplete
    def __init__(self, data) -> None: ...
    @staticmethod
    def gzip_if_smaller(content_related, data): ...
    def __bytes__(self) -> bytes: ...
    @staticmethod
    def read(reader): ...
    @classmethod
    def from_reader(cls, reader): ...
    def to_dict(self): ...
