from .. import __version__ as __version__, constants as constants
from typing import Any

def is_package_available(package_name: str) -> bool: ...
def get_python_version() -> str: ...
def get_hf_hub_version() -> str: ...
def is_aiohttp_available() -> bool: ...
def get_aiohttp_version() -> str: ...
def is_fastai_available() -> bool: ...
def get_fastai_version() -> str: ...
def is_fastapi_available() -> bool: ...
def get_fastapi_version() -> str: ...
def is_fastcore_available() -> bool: ...
def get_fastcore_version() -> str: ...
def is_gradio_available() -> bool: ...
def get_gradio_version() -> str: ...
def is_graphviz_available() -> bool: ...
def get_graphviz_version() -> str: ...
def is_hf_transfer_available() -> bool: ...
def get_hf_transfer_version() -> str: ...
def is_keras_available() -> bool: ...
def get_keras_version() -> str: ...
def is_numpy_available() -> bool: ...
def get_numpy_version() -> str: ...
def is_jinja_available() -> bool: ...
def get_jinja_version() -> str: ...
def is_pillow_available() -> bool: ...
def get_pillow_version() -> str: ...
def is_pydantic_available() -> bool: ...
def get_pydantic_version() -> str: ...
def is_pydot_available() -> bool: ...
def get_pydot_version() -> str: ...
def is_tensorboard_available() -> bool: ...
def get_tensorboard_version() -> str: ...
def is_tf_available() -> bool: ...
def get_tf_version() -> str: ...
def is_torch_available() -> bool: ...
def get_torch_version() -> str: ...
def is_safetensors_available() -> bool: ...
def is_notebook() -> bool: ...
def is_google_colab() -> bool: ...
def is_colab_enterprise() -> bool: ...
def dump_environment_info() -> dict[str, Any]: ...
