import io
from ..constants import HF_HUB_DISABLE_PROGRESS_BARS as HF_HUB_DISABLE_PROGRESS_BARS
from pathlib import Path
from tqdm.auto import tqdm as old_tqdm
from typing import Iterator

progress_bar_states: dict[str, bool]

def disable_progress_bars(name: str | None = None) -> None: ...
def enable_progress_bars(name: str | None = None) -> None: ...
def are_progress_bars_disabled(name: str | None = None) -> bool: ...

class tqdm(old_tqdm):
    def __init__(self, *args, **kwargs) -> None: ...
    def __delattr__(self, attr: str) -> None: ...

def tqdm_stream_file(path: Path | str) -> Iterator[io.BufferedReader]: ...
