completions:
  - model: "Qwen/Qwen2.5-Coder-32B-Instruct"
  - model: "Qwen/Qwen2.5-72B-Instruct"
  - model: "meta-llama/Llama-3.3-70B-Instruct"
  - model: "deepseek-r1"
    type: "ollama"
images:
  - model: "black-forest-labs/FLUX.1-dev"
  - model: "stabilityai/stable-diffusion-3.5-large"
  - model: "stabilityai/stable-diffusion-3-medium"
  - model: "stabilityai/stable-diffusion-xl-base-1.0"
