[tool.poetry]
name = "tgbot"
version = "0.1.0"
description = ""
authors = ["Li Hua <lihua@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
python-dotenv = "^1.0.1"
huggingface-hub = "^0.26.5"
aiohttp = "^3.11.10"
telethon = "^1.38.1"

[tool.basedpyright]
typeCheckingMode = "standard"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
fixable = ["ALL"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
