[project]
name = "tgbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.11",
    "huggingface-hub>=0.27.0",
    "portalocker>=3.0.0",
    "python-dotenv>=1.0.1",
    "regex>=2024.11.6",
    "telethon>=1.38.1",
]

[tool.basedpyright]
typeCheckingMode = "standard"

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
fixable = ["ALL"]
