import abc
from . import helpers as helpers
from _typeshed import Incomplete

class RequestIter(abc.ABC, metaclass=abc.ABCMeta):
    client: Incomplete
    reverse: Incomplete
    wait_time: Incomplete
    kwargs: Incomplete
    limit: Incomplete
    left: Incomplete
    buffer: Incomplete
    index: int
    total: Incomplete
    last_load: int
    def __init__(self, client, limit, *, reverse: bool = False, wait_time: Incomplete | None = None, **kwargs) -> None: ...
    async def __anext__(self): ...
    def __next__(self): ...
    def __aiter__(self): ...
    def __iter__(self): ...
    async def collect(self): ...
    def __reversed__(self): ...
