from .base import BaseInferenceType as BaseInferenceType
from _typeshed import Incomplete
from dataclasses import dataclass

FeatureExtractionInputTruncationDirection: Incomplete

@dataclass
class FeatureExtractionInput(BaseInferenceType):
    inputs: str
    normalize: bool | None = ...
    prompt_name: str | None = ...
    truncate: bool | None = ...
    truncation_direction: FeatureExtractionInputTruncationDirection | None = ...
    def __init__(self, inputs, normalize=..., prompt_name=..., truncate=..., truncation_direction=...) -> None: ...
