from . import constants as constants
from .commands._cli_utils import ANSI as ANSI
from .utils import capture_output as capture_output, get_token as get_token, is_google_colab as is_google_colab, is_notebook as is_notebook, list_credential_helpers as list_credential_helpers, logging as logging, run_subprocess as run_subprocess, set_git_credential as set_git_credential, unset_git_credential as unset_git_credential
from .utils._auth import get_stored_tokens as get_stored_tokens
from _typeshed import Incomplete

logger: Incomplete

def login(token: str | None = None, add_to_git_credential: bool = False, new_session: bool = True, write_permission: bool = False) -> None: ...
def logout(token_name: str | None = None) -> None: ...
def auth_switch(token_name: str, add_to_git_credential: bool = False) -> None: ...
def auth_list() -> None: ...
def interpreter_login(new_session: bool = True, write_permission: bool = False) -> None: ...

NOTEBOOK_LOGIN_PASSWORD_HTML: str
NOTEBOOK_LOGIN_TOKEN_HTML_START: str
NOTEBOOK_LOGIN_TOKEN_HTML_END: str

def notebook_login(new_session: bool = True, write_permission: bool = False) -> None: ...
