import gradio as gr
from .utils import experimental as experimental, is_fastapi_available as is_fastapi_available, is_gradio_available as is_gradio_available
from _typeshed import Incomplete
from typing import Any, Callable

class WebhooksServer:
    def __new__(cls, *args, **kwargs) -> WebhooksServer: ...
    webhook_secret: Incomplete
    registered_webhooks: Incomplete
    def __init__(self, ui: gr.Blocks | None = None, webhook_secret: str | None = None) -> None: ...
    def add_webhook(self, path: str | None = None) -> Callable: ...
    def launch(self, prevent_thread_lock: bool = False, **launch_kwargs: Any) -> None: ...

def webhook_endpoint(path: str | None = None) -> Callable: ...
