from ...tl import types as types
from ...utils import get_input_peer as get_input_peer
from _typeshed import Incomplete

class AdminLogEvent:
    original: Incomplete
    entities: Incomplete
    user: Incomplete
    input_user: Incomplete
    def __init__(self, original, entities) -> None: ...
    @property
    def id(self): ...
    @property
    def date(self): ...
    @property
    def user_id(self): ...
    @property
    def action(self): ...
    @property
    def old(self): ...
    @property
    def new(self): ...
    @property
    def changed_about(self): ...
    @property
    def changed_title(self): ...
    @property
    def changed_username(self): ...
    @property
    def changed_photo(self): ...
    @property
    def changed_sticker_set(self): ...
    @property
    def changed_message(self): ...
    @property
    def deleted_message(self): ...
    @property
    def changed_admin(self): ...
    @property
    def changed_restrictions(self): ...
    @property
    def changed_invites(self): ...
    @property
    def changed_location(self): ...
    @property
    def joined(self): ...
    @property
    def joined_invite(self): ...
    @property
    def left(self): ...
    @property
    def changed_hide_history(self): ...
    @property
    def changed_signatures(self): ...
    @property
    def changed_pin(self): ...
    @property
    def changed_default_banned_rights(self): ...
    @property
    def stopped_poll(self): ...
    @property
    def started_group_call(self): ...
    @property
    def discarded_group_call(self): ...
    @property
    def user_muted(self): ...
    @property
    def user_unmutted(self): ...
    @property
    def changed_call_settings(self): ...
    @property
    def changed_history_ttl(self): ...
    @property
    def deleted_exported_invite(self): ...
    @property
    def edited_exported_invite(self): ...
    @property
    def revoked_exported_invite(self): ...
    @property
    def joined_by_invite(self): ...
    @property
    def changed_user_volume(self): ...
    def stringify(self): ...
