import abc
from ... import errors as errors, utils as utils
from ...tl import types as types
from _typeshed import Incomplete

class ChatGetter(abc.ABC):
    def __init__(self, chat_peer: Incomplete | None = None, *, input_chat: Incomplete | None = None, chat: Incomplete | None = None, broadcast: Incomplete | None = None) -> None: ...
    @property
    def chat(self): ...
    async def get_chat(self): ...
    @property
    def input_chat(self): ...
    async def get_input_chat(self): ...
    @property
    def chat_id(self): ...
    @property
    def is_private(self): ...
    @property
    def is_group(self): ...
    @property
    def is_channel(self): ...
