from ... import utils as utils
from ...tl import types as types
from _typeshed import Incomplete

class File:
    media: Incomplete
    def __init__(self, media) -> None: ...
    @property
    def id(self): ...
    @property
    def name(self): ...
    @property
    def ext(self): ...
    @property
    def mime_type(self): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def duration(self): ...
    @property
    def title(self): ...
    @property
    def performer(self): ...
    @property
    def emoji(self): ...
    @property
    def sticker_set(self): ...
    @property
    def size(self): ...
