from .. import functions as functions, types as types
from ... import utils as utils
from _typeshed import Incomplete

class InlineBuilder:
    def __init__(self, client) -> None: ...
    async def article(self, title, description: Incomplete | None = None, *, url: Incomplete | None = None, thumb: Incomplete | None = None, content: Incomplete | None = None, id: Incomplete | None = None, text: Incomplete | None = None, parse_mode=(), link_preview: bool = True, geo: Incomplete | None = None, period: int = 60, contact: Incomplete | None = None, game: bool = False, buttons: Incomplete | None = None): ...
    async def photo(self, file, *, id: Incomplete | None = None, include_media: bool = True, text: Incomplete | None = None, parse_mode=(), link_preview: bool = True, geo: Incomplete | None = None, period: int = 60, contact: Incomplete | None = None, game: bool = False, buttons: Incomplete | None = None): ...
    async def document(self, file, title: Incomplete | None = None, *, description: Incomplete | None = None, type: Incomplete | None = None, mime_type: Incomplete | None = None, attributes: Incomplete | None = None, force_document: bool = False, voice_note: bool = False, video_note: bool = False, use_cache: bool = True, id: Incomplete | None = None, text: Incomplete | None = None, parse_mode=(), link_preview: bool = True, geo: Incomplete | None = None, period: int = 60, contact: Incomplete | None = None, game: bool = False, buttons: Incomplete | None = None, include_media: bool = True): ...
    async def game(self, short_name, *, id: Incomplete | None = None, text: Incomplete | None = None, parse_mode=(), link_preview: bool = True, geo: Incomplete | None = None, period: int = 60, contact: Incomplete | None = None, game: bool = False, buttons: Incomplete | None = None): ...
