from .. import functions as functions, types as types
from ...errors import BotResponseTimeoutError as BotResponseTimeoutError
from _typeshed import Incomplete

class MessageButton:
    button: Incomplete
    def __init__(self, client, original, chat, bot, msg_id) -> None: ...
    @property
    def client(self): ...
    @property
    def text(self): ...
    @property
    def data(self): ...
    @property
    def inline_query(self): ...
    @property
    def url(self): ...
    async def click(self, share_phone: Incomplete | None = None, share_geo: Incomplete | None = None, *, password: Incomplete | None = None): ...
