import datetime
from .. import functions as functions, types as types
from ... import events as events

class QRLogin:
    def __init__(self, client, ignored_ids) -> None: ...
    async def recreate(self) -> None: ...
    @property
    def token(self) -> bytes: ...
    @property
    def url(self) -> str: ...
    @property
    def expires(self) -> datetime.datetime: ...
    async def wait(self, timeout: float = None): ...
