import abc
from ... import utils as utils
from _typeshed import Incomplete

class SenderGetter(abc.ABC):
    def __init__(self, sender_id: Incomplete | None = None, *, sender: Incomplete | None = None, input_sender: Incomplete | None = None) -> None: ...
    @property
    def sender(self): ...
    async def get_sender(self): ...
    @property
    def input_sender(self): ...
    async def get_input_sender(self): ...
    @property
    def sender_id(self): ...
