from .. import alltlobjects as alltlobjects, types as types
from ..custom.message import Message as _Message

class MessageEmpty(_Message, types.MessageEmpty): ...
class MessageService(_Message, types.MessageService): ...
class Message(_Message, types.Message): ...
