# generated by datamodel-codegen:
#   filename:  delete_messages.json
#   timestamp: 2025-02-02T00:45:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class DeleteMessages(BaseModel):
    message_ids: List = Field(..., description="The IDs to be deleted.")
