# generated by datamodel-codegen:
#   filename:  kick_participant.json
#   timestamp: 2025-02-02T01:02:24+00:00

from __future__ import annotations

from openai import pydantic_function_tool
from pydantic import BaseModel, Field

from . import Tool


@Tool
@pydantic_function_tool
class KickParticipant(BaseModel):
    user: int = Field(..., description="The user to kick.")
