# generated by datamodel-codegen:
#   filename:  kick_participant.json
#   timestamp: 2025-02-02T01:02:24+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class KickParticipant(BaseModel):
    user: int = Field(..., description='The user to kick.')
