# generated by datamodel-codegen:
#   filename:  SetBotInfoRequest.json
#   timestamp: 2025-02-02T01:14:05+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class SetBotInfoRequest(BaseModel):
    lang_code: str = Field(..., description='lang code')
    name: Optional[str] = Field(
        None,
        description='Your name. This argument defaults to `None` and can be omitted.',
    )
    about: Optional[str] = Field(
        None,
        description='Information about you. This argument defaults to `None` and can be omitted.',
    )
    description: Optional[str] = Field(
        None,
        description='A description of you. This argument defaults to `None` and can be omitted.',
    )
