# generated by datamodel-codegen:
#   filename:  text_to_image.json
#   timestamp: 2025-02-02T01:15:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import Tool


@Tool
class images(BaseModel):
    prompt: str = Field(..., description="A text description of the desired image(s)")
    size: Optional[str] = Field(
        ...,
        description="The size of the generated images.",
    )
