# generated by datamodel-codegen:
#   filename:  unpin_message.json
#   timestamp: 2025-02-02T01:16:50+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import Tool


@Tool
class UnpinMessage(BaseModel):
    message: int = Field(
        ...,
        description="消息ID，可从Telegram消息链接获取, 例如：https://t.me/{chat_id}/{message_id}",
    )
