from _typeshed import Incomplete

class TLObject:
    CONSTRUCTOR_ID: Incomplete
    SUBCLASS_OF_ID: Incomplete
    @staticmethod
    def pretty_format(obj, indent: Incomplete | None = None): ...
    @staticmethod
    def serialize_bytes(data): ...
    @staticmethod
    def serialize_datetime(dt): ...
    def __eq__(self, o): ...
    def __ne__(self, o): ...
    def stringify(self): ...
    def to_dict(self) -> None: ...
    def to_json(self, fp: Incomplete | None = None, default=..., **kwargs): ...
    def __bytes__(self) -> bytes: ...
    @classmethod
    def from_reader(cls, reader) -> None: ...

class TLRequest(TLObject):
    @staticmethod
    def read_result(reader): ...
    async def resolve(self, client, utils) -> None: ...
