from .. import utils as utils
from .common import EventBuilder as EventBuilder
from _typeshed import Incomplete

class Raw(EventBuilder):
    types: Incomplete
    def __init__(self, types: Incomplete | None = None, *, func: Incomplete | None = None) -> None: ...
    resolved: bool
    async def resolve(self, client) -> None: ...
    @classmethod
    def build(cls, update, others: Incomplete | None = None, self_id: Incomplete | None = None): ...
    def filter(self, event): ...
