from .session import Entity as Entity, EntityType as EntityType
from _typeshed import Incomplete

class EntityCache:
    hash_map: Incomplete
    self_id: Incomplete
    self_bot: Incomplete
    def __init__(self, hash_map: dict = ..., self_id: int = None, self_bot: bool = None) -> None: ...
    def set_self_user(self, id, bot, hash) -> None: ...
    def get(self, id): ...
    def extend(self, users, chats) -> None: ...
    def get_all_entities(self): ...
    def put(self, entity) -> None: ...
    def retain(self, filter) -> None: ...
    def __len__(self) -> int: ...
