from ..extensions import BinaryReader as BinaryReader
from _typeshed import Incomplete

class AuthKey:
    def __init__(self, data) -> None: ...
    @property
    def key(self): ...
    aux_hash: Incomplete
    key_id: Incomplete
    @key.setter
    def key(self, value) -> None: ...
    def calc_new_nonce_hash(self, new_nonce, number): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
