from .rpcbaseerrors import AuthKeyError as AuthKeyError, BadRequestError as BadRequestError, FloodError as FloodError, ForbiddenError as ForbiddenError, InvalidDCError as InvalidDCError, RPCError as RPCError, ServerError as ServerError, TimedOutError as TimedOutError, UnauthorizedError as UnauthorizedError
from _typeshed import Incomplete

class TwoFaConfirmWaitError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class AboutTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AccessTokenExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AccessTokenInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ActiveUserRequiredError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AdminsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AdminIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AdminRankEmojiNotAllowedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AdminRankInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AlbumPhotosTooManyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ApiIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ApiIdPublishedFloodError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ArticleTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AudioContentUrlEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AudioTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthBytesInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthKeyDuplicatedError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthKeyInvalidError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthKeyPermEmptyError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthKeyUnregisteredError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthRestartError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenAlreadyAcceptedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenExceptionError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenInvalid2Error(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AuthTokenInvalidxError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class AutoarchiveNotAvailableError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BankCardNumberInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BannedRightsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BasePortLocInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotChannelsNaError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotCommandDescriptionInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotCommandInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotDomainInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotGamesDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotGroupsBlockedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotInlineDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotMethodInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotOnesideNotAvailError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotPaymentsDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotPollsDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotResponseTimeoutError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BotScoreNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BroadcastCallsDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BroadcastForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BroadcastIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BroadcastPublicVotersForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class BroadcastRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ButtonDataInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ButtonTextInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ButtonTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ButtonUrlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ButtonUserPrivacyRestrictedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CallAlreadyAcceptedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CallAlreadyDeclinedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CallOccupyFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CallPeerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CallProtocolFlagsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CdnMethodInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CdnUploadTimeoutError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelsAdminLocatedTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelsAdminPublicTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelBannedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelForumMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelParicipantMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelPrivateError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelPublicGroupNaError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelTooBigError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChannelTooLargeError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatAboutNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatAboutTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatAdminInviteRequiredError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatAdminRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatDiscussionUnallowedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatForwardsRestrictedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatGetFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatGuestSendForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatIdEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatIdGenerateFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatInvitePermanentError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatLinkExistsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatRestrictedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatRevokeDateUnsupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendGameForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendGifsForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendInlineForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendMediaForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendPollForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatSendStickersForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatTooBigError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChatWriteForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ChpCallFailError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CodeEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CodeHashInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CodeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionApiIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionAppVersionEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionDeviceModelEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionLangPackInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionLayerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionNotInitedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionSystemEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ConnectionSystemLangCodeEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ContactAddMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ContactIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ContactNameEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ContactReqMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CreateCallFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class CurrencyTotalAmountInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DataInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DataJsonInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DataTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DateEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DcIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DhGAInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class DocumentInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EditBotInviteForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmailHashExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmailInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmailUnconfirmedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmailUnconfirmedError(BadRequestError):
    request: Incomplete
    code_length: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class EmailVerifyExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmojiInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmojiNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmoticonEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmoticonInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EmoticonStickerpackMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptedMessageInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptionAlreadyAcceptedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptionAlreadyDeclinedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptionDeclinedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptionIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EncryptionOccupyFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EntitiesTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EntityBoundsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class EntityMentionUserInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ErrorTextEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ExpireDateInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ExpireForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ExportCardInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ExternalUrlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FieldNameEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FieldNameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilerefUpgradeNeededError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileContentTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileEmtpyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileMigrateError(InvalidDCError):
    request: Incomplete
    new_dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class FilePartsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePart0MissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartLengthInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartSizeChangedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartSizeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartTooBigError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilePartMissingError(BadRequestError):
    request: Incomplete
    which: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class FileReferenceEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileReferenceExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileReferenceInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FileTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilterIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilterIncludeEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilterNotSupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FilterTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FirstNameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FloodTestPhoneWaitError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class FloodWaitError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class FloodPremiumWaitError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class FolderIdEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FolderIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FreshChangeAdminsForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FreshChangePhoneForbiddenError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FreshResetAuthorisationForbiddenError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FromMessageBotDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class FromPeerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GameBotInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GeoPointInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GifContentTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GifIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GraphExpiredReloadError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GraphInvalidReloadError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GraphOutdatedReloadError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallAddParticipantsFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallAlreadyDiscardedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallAlreadyStartedError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallJoinMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupcallSsrcDuplicateMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupedMediaInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class GroupCallInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class HashInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class HideRequesterMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class HistoryGetFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ImageProcessFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ImportFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ImportFormatUnrecognizedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ImportIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InlineBotRequiredError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InlineResultExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputConstructorInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputFetchErrorError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputFetchFailError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputFilterInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputLayerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputMethodInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputRequestTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputTextEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InputUserDeactivatedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InterdcCallErrorError(ServerError):
    request: Incomplete
    dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class InterdcCallRichErrorError(ServerError):
    request: Incomplete
    dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class InviteForbiddenWithJoinasError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InviteHashEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InviteHashExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InviteHashInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InviteRequestSentError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InviteRevokedMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class InvoicePayloadInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class JoinAsPeerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LangCodeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LangCodeNotSupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LangPackInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LastnameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LimitInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LinkNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class LocationInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MaxDateInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MaxIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MaxQtsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class Md5ChecksumInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaCaptionTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaGroupedInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaNewInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaPrevInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MediaTtlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MegagroupIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MegagroupPrehistoryHiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MegagroupRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MemberNoLocationError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MemberOccupyPrimaryLocFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageAuthorRequiredError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageDeleteForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageEditTimeExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageIdsEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessagePollClosedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MessageTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MethodInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MinDateInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MsgidDecreaseRetryError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MsgIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MsgTooOldError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MsgWaitFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MtSendQueueTooLongError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class MultiMediaTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NeedChatInvalidError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NeedMemberInvalidError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NetworkMigrateError(InvalidDCError):
    request: Incomplete
    new_dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class NewSaltInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NewSettingsEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NewSettingsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NextOffsetInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class NotAllowedError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class OffsetInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class OffsetPeerIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class OptionsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class OptionInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PackShortNameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PackShortNameOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PackTitleInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ParticipantsTooFewError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ParticipantCallFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ParticipantIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ParticipantJoinMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ParticipantVersionOutdatedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordHashInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordRecoveryExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordRecoveryNaError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PasswordTooFreshError(BadRequestError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class PaymentProviderInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PeerFloodError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PeerHistoryEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PeerIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PeerIdNotSupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PersistentTimestampEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PersistentTimestampInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PersistentTimestampOutdatedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneCodeEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneCodeExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneCodeHashEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneCodeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneHashExpiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneMigrateError(InvalidDCError):
    request: Incomplete
    new_dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class PhoneNotOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberAppSignupForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberBannedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberFloodError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhoneNumberUnoccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhonePasswordFloodError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhonePasswordProtectedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoContentTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoContentUrlEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoCropFileMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoCropSizeSmallError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoExtInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoFileMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoInvalidDimensionsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoSaveFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PhotoThumbUrlEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PinnedDialogsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PinRestrictedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollAnswersInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollAnswerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollOptionDuplicateError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollOptionInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollQuestionInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollUnsupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PollVoteRequiredError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PostponedTimeoutError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PremiumAccountRequiredError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PremiumCurrentlyUnavailableError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PreviousChatImportActiveWaitMinError(AuthKeyError):
    request: Incomplete
    minutes: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class PrivacyKeyInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PrivacyTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PrivacyValueInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PtsChangeEmptyError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PublicChannelMissingError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class PublicKeyRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QueryIdEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QueryIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QueryTooShortError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QuizAnswerMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QuizCorrectAnswersEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QuizCorrectAnswersTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QuizCorrectAnswerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class QuizMultipleInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RandomIdDuplicateError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RandomIdEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RandomIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RandomLengthInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RangesInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReactionsTooManyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReactionEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReactionInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReflectorNotAvailableError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RegIdGenerateFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReplyMarkupBuyEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReplyMarkupGameEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReplyMarkupInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ReplyMarkupTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResetRequestMissingError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResultsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResultIdDuplicateError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResultIdEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResultIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ResultTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RevoteNotAllowedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RightsNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RightForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RpcCallFailError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RpcMcgetFailError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class RsaDecryptFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScheduleBotNotAllowedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScheduleDateInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScheduleDateTooLateError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScheduleStatusPrivateError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScheduleTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ScoreInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SearchQueryEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SearchWithLinkNotSupportedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SecondsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SendAsPeerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SendCodeUnavailableError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SendMessageMediaInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SendMessageTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SensitiveChangeForbiddenError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SessionExpiredError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SessionPasswordNeededError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SessionRevokedError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SessionTooFreshError(BadRequestError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class SettingsInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class Sha256HashInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ShortnameOccupyFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ShortNameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ShortNameOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SignInFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SlowModeMultiMsgsDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SlowModeWaitError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class SmsCodeCreateFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SrpIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SrpPasswordChangedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StartParamEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StartParamInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StartParamTooLongError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StatsMigrateError(InvalidDCError):
    request: Incomplete
    dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class StickerpackStickersTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickersetInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickersetOwnerAnonymousError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickersEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickersTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerDocumentInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerEmojiInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerGifDimensionsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerMimeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerPngDimensionsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerPngNopngError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerTgsNodocError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerTgsNotgsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerThumbPngNopngError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerThumbTgsNotgsError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerVideoBigError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerVideoNodocError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StickerVideoNowebmError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StorageCheckFailedError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class StoreInvalidScalarTypeError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class SwitchPmTextEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TakeoutInitDelayError(FloodError):
    request: Incomplete
    seconds: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class TakeoutInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TakeoutRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TempAuthKeyAlreadyBoundError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TempAuthKeyEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ThemeFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ThemeFormatInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ThemeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ThemeMimeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ThemeTitleInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TimeoutError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TitleInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TmpPasswordDisabledError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TmpPasswordInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TokenInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TopicDeletedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class ToLangInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TtlDaysInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TtlMediaInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TtlPeriodInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TypesEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TypeConstructorInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TimedoutError(TimedOutError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class TimeoutError(TimedOutError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UnknownErrorError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UnknownMethodError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UntilDateInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UpdateAppToLoginError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UrlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsageLimitInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsernameInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsernameNotModifiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsernameNotOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsernameOccupiedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsernamePurchaseAvailableError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserpicPrivacyRequiredError(AuthKeyError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserpicUploadRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsersTooFewError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UsersTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserAdminInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserAlreadyInvitedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserAlreadyParticipantError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserBannedInChannelError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserBlockedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserBotError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserBotInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserBotRequiredError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserChannelsTooMuchError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserCreatorError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserDeactivatedError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserDeactivatedBanError(UnauthorizedError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserDeletedError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserIdInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserIsBlockedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserIsBotError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserKickedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserMigrateError(InvalidDCError):
    request: Incomplete
    new_dc: Incomplete
    def __init__(self, request, capture: int = 0) -> None: ...
    def __reduce__(self): ...

class UserNotMutualContactError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserNotParticipantError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserPrivacyRestrictedError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserRestrictedError(ForbiddenError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class UserVolumeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class VideoContentTypeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class VideoFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class VideoTitleEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class VoiceMessagesForbiddenError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WallpaperFileInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WallpaperInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WallpaperMimeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WcConvertUrlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebdocumentInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebdocumentMimeInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebdocumentSizeTooBigError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebdocumentUrlInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebpageCurlFailedError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebpageMediaEmptyError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebpushAuthInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebpushKeyInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WebpushTokenInvalidError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class WorkerBusyTooLongRetryError(ServerError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

class YouBlockedUserError(BadRequestError):
    request: Incomplete
    def __init__(self, request) -> None: ...
    def __reduce__(self): ...

rpc_errors_dict: Incomplete
rpc_errors_re: Incomplete
