on:
  push:
    branches:
    - slave
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'sync'
        git push ${{ secrets.REPO_URL }} slave:main -f
