on:
  push:
    branches:
    - slave
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          lfs: true
    - run: git push ${{ secrets.REPO_URL }} slave:main -f
